# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Lotus Base blog"
email: hello@lotus.au.dk
description: > # this means to ignore newlines until "baseurl:"
  The developer's blog for Lotus Base
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://lotus.au.dk" # the base hostname & protocol for your site
twitter_username: lotusbase
github_username:  lotusbase

# Build settings
markdown: kramdown

# Other settings
webroot: ""

# Allow related post indexing
lsi: true

# Use SASS
sass:
  sass_dir: src/css
  style: compressed